name: Release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main 

      - name: Create Package
        run: tar -czf apachenest.tar.gz --exclude LICENSE --exclude README.md --exclude CODE_OF_CONDUCT.md --exclude CONTRIBUTING.md *

      - name: Generate Changelog
        id: changelog
        run: .github/scripts/changelog.sh > CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        continue-on-error: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: steps.changelog.outcome == 'success'
        with:
          body_path: CHANGELOG.md
          files: apachenest.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
